[features]
seeds = false
skip-lint = false

[programs.localnet]
perpetual_yield_token = "FkQpVUX5iRw5Gft6Co1iKJDnufEA3FYBsGJS87RaT4nf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
